trigger: 
  - none

variables:
  - group: Terraform_SPN

stages:
- stage: TerraformInitApply
  jobs:
  - job: Terraform1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: SP_AzureRM_Pokroy_Testing
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Install Terraform
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 14
          curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          unzip terraform_1.0.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          
          # Initialize Terraform
          terraform init -backend-config="storage_account_name=$(STORAGE_ACCOUNT_NAME)" \
                         -backend-config="container_name=$(CONTAINER_NAME)" \
                         -backend-config="key=$(KEY)" \
                         -backend-config="access_key=$(ACCESS_KEY)"
          # Apply Terraform configuration
          terraform apply -auto-approve

