trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'SP_AzureRM_Pokroy_Testing'                    ## YOUR_SERVICE_CONNECTION_NAME
    KeyVaultName: 'key-vault-testing-01'                         ## YOUR_KEY_VAULT_NAME
    SecretsFilter: 'test'                          ## YOUR_SECRET_NAME. Default value: *
    RunAsPreJob: false

- script: | 
    echo "vamos"  


