trigger:
  - develop_keyvault

pool:
  vmImage: 'ubuntu-latest'

variables:
  sp_name: 'SP_AzureRM_Pokroy_Testing'
  keyvault_name: 'key-vault-testing-01'
  
steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: $(sp_name)                  
    KeyVaultName: $(keyvault_name)                        
    SecretsFilter: 'test'                         
    RunAsPreJob: false

- script: | 
    echo "vamos" 
    echo $(test)


